const xlsx = require("xlsx");
import { app, database, storage } from "@/firebaseConfig";
import { Button, ThemeProvider, createTheme } from "@mui/material";
import Autocomplete from "@mui/material/Autocomplete";
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { DatePicker } from "@mui/x-date-pickers/DatePicker";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { Inter } from "@next/font/google";
import { FaFileUpload } from "react-icons/fa";
import { MdAccountCircle, MdPersonAdd } from "react-icons/md";

import { addDoc, collection } from "firebase/firestore";
import { getDownloadURL, ref, uploadBytes } from "firebase/storage";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Navbar2 from "../components/Navbar2";
import ParticleBackground from "../components/particleBackground";
const inter = Inter({ subsets: ["latin"] });

// const db = firebase.firestore();

export default function Notes() {
  //theme for mui
  const theme = createTheme({
    palette: {
      mode: "dark",
      primary: {
        main: "#e6e6e6",
        contrastText: "#fff",
      },
    },
  });
  const subjectOptions = ["Subject 1", "Subject 2", "Subject 3"];
  //subject
  const subCodeOptions = ["Sub code 1", "Sub code 2", "Sub code 3"];
  const semesterOptions = [
    "Semester 1",
    "Semester 2",
    "Semester 3",
    "Semester 4",
    "Semester 5",
    "Semester 6",
    "Semester 7",
    "Semester 8",
  ];

  const router = useRouter();

  const [subjectName, setsubjectName] = useState("");
  const [subCode, setsubCode] = useState("");
  const [dop, setDop] = useState("");
  const [sem, setSem] = useState("");
  const [pdf, setpdfFile] = useState(null);
  const handleFileChange = (e) => {
    const file = e.target.files[0];
    setpdfFile(file);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      const storageRef = ref(storage, `pdfs/${pdf.name}`);
      await uploadBytes(storageRef, pdf);

      const pdfUrl = await getDownloadURL(storageRef);

      const docRef = await addDoc(collection(database, "documents"), {
        subjectName,
        subCode,
        dop,
        sem,
        pdfUrl,
      });

      console.log("Document written with ID: ", docRef.id);
    } catch (error) {
      console.error("Error adding document: ", error);
    }
  };
  return (
    <>
      <Head>
        <title>Add Co admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <Navbar2 />
      <main>
        <ParticleBackground />
        <div className="h-auto  flex flex-col justify-center items-center py-8 ">
          <div
            style={{ zIndex: "1" }}
            className="  px-12 py-10 w-11/12 sm:w-10/12 md:w-4/5 lg:w-4/5 xl:w-1/2 glass-morphic border-2 border-black rounded-md flex flex-col box-border"
          >
            <div className="text-5xl text-white text-center">Add Mentor</div>
            {/* <di v className="text-5x text-center">
              Upload Notes
            </di> */}
            {/* <div className="h-1" /> */}

            <div className="flex flex-col  ">
              <ThemeProvider theme={theme}>
                <div className="flex flex-col mt-10 mb-10">
                  <TextField fullWidth label="Mentor Name" id="fullWidth" />
                </div>

                <div className="flex flex-col mb-10 ">
                  <TextField fullWidth label="Employee ID" id="fullWidth" />
                </div>

                <Button
                  variant="outlined"
                  sx={{
                    fontSize: "1.2rem",
                    padding: "10px 0",
                    maxwidth: 240,
                  }}
                  endIcon={<MdPersonAdd style={{ fontSize: "1.5rem" }} />}
                  onClick={handleSubmit}
                >
                  Add
                </Button>
              </ThemeProvider>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
