const xlsx = require("xlsx");
import { app, database, getMessaging, storage } from "@/firebaseConfig";
import { Button, ThemeProvider, createTheme } from "@mui/material";
import FormControl from "@mui/material/FormControl";
import InputLabel from "@mui/material/InputLabel";
import MenuItem from "@mui/material/MenuItem";
import Select from "@mui/material/Select";
import TextField from "@mui/material/TextField";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { DatePicker } from "@mui/x-date-pickers/DatePicker";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { Inter } from "@next/font/google";
import { addDoc, collection } from "firebase/firestore";
import { getDownloadURL, ref, uploadBytesResumable } from "firebase/storage";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { FaFileUpload } from "react-icons/fa";
import { MdSend } from "react-icons/md";
import Navbar2 from "../components/Navbar2";
import ParticleBackground from "../components/particleBackground";
const inter = Inter({ subsets: ["latin"] });

export default function NotifyMe() {
  const theme = createTheme({
    palette: {
      mode: "dark",
      primary: {
        main: "#e6e6e6",
        contrastText: "#fff",
      },
    },
  });
  const [Category, setCategory] = useState("");
  const [title, settitle] = useState("");
  const [contentpara, setcontentpara] = useState("");
  const [dop, setDop] = useState("");
  const [excelFile, setexcelFile] = useState(null);
  const [percent, setPercent] = useState(0);

  return (
    <>
      <Head>
        <title>Marks Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <header>
        <Navbar2 />
      </header>
      <main>
        <ParticleBackground />
        <div className="h-auto flex flex-col justify-center items-center py-8  ">
          <div
            style={{ zIndex: "1" }}
            className="px-12 py-10 w-11/12 sm:w-10/12 md:w-4/5 lg:w-4/5 xl:w-1/2 glass-morphic border-2 border-black rounded-md flex flex-col box-border"
          >
            <div className="text-5xl text-white text-center">
              Send Notification
            </div>

            <ThemeProvider theme={theme}>
              <div className="flex flex-col px-10">
                <div className="flex flex-col mt-10 mb-10">
                  <FormControl fullWidth>
                    <InputLabel id="demo-simple-select-label">
                      Category of Notification
                    </InputLabel>
                    <Select
                      labelId="Category-of-Notification"
                      id="Notification-select"
                      value={Category}
                      label="Category of Notification"
                      onChange={(e) => {
                        setCategory(e.target.value);
                      }}
                    >
                      <MenuItem value={"Exam Notification"}>
                        Exam Notification
                      </MenuItem>
                      <MenuItem value={"cultural events"}>
                        Cultural events
                      </MenuItem>
                      <MenuItem value={"Sports"}>Sports</MenuItem>
                      <MenuItem value={"placement"}>Placement</MenuItem>
                    </Select>
                  </FormControl>
                </div>
                <div className="flex flex-col  mb-10">
                  <TextField
                    id="outlined-basic"
                    value={title}
                    sx={{ maxwidth: 500 }}
                    onChange={(e) => {
                      settitle(e.target.value);
                    }}
                    label="Enter title here"
                    variant="outlined"
                  />
                </div>
                <div className="flex flex-col mb-10">
                  <TextField
                    id="content"
                    label="Content"
                    sx={{ maxwidth: 500 }}
                    value={contentpara}
                    onChange={(e) => {
                      setcontentpara(e.target.value);
                    }}
                    multiline
                    rows={6}
                  />
                </div>

                <div className="flex flex-row gap-6  flex-wrap justify-center">
                  <LocalizationProvider dateAdapter={AdapterDayjs}>
                    <DatePicker
                      label="Select Date"
                      onChange={(event, selectedValue) => {
                        setDop(selectedValue);
                      }}
                      renderInput={(params) => (
                        <TextField {...params} label="Select a Date" />
                      )}
                    />
                  </LocalizationProvider>

                  <div className="flex flex-col  mb-10">
                    <label
                      htmlFor="filePicker"
                      className="block font-medium mb-2"
                    >
                      <Button
                        component="span"
                        variant="outlined"
                        sx={{
                          padding: "13px",
                          // minWidth: 310,
                          textTransform: "capitalize",
                          color: "rgba(255, 255, 255, 0.7)",
                          fontWeight: "400",
                          fontSize: "1rem",
                        }}
                      >
                        Select Notification Attachment
                        <FaFileUpload
                          fontSize="1.45em"
                          style={{
                            marginLeft: "auto",
                            marginLeft: "10px",
                            color: "rgba(255, 255, 255, 1)",
                          }}
                        />
                      </Button>
                    </label>
                    <input
                      type="file"
                      id="filePicker"
                      style={{ display: "none" }}
                      accept=".pdf"
                      // onChange={handleFileChange}
                      className="py-2 px-4 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
                    />
                  </div>
                </div>

                <Button
                  variant="outlined"
                  sx={{
                    fontSize: "1.2rem",
                    padding: "10px 0",
                  }}
                  endIcon={<MdSend />}
                  onClick={handleSubmit}
                >
                  Submit
                </Button>
              </div>
            </ThemeProvider>
          </div>
        </div>
      </main>
    </>
  );
}
